# gossh -e=1 -c testdata/centos_build.toml -H "user:xxx@192.168.1.75" at ..

#printConfig = true
#passphrase="xxxx"
group = "1"

hosts = [
    "192.168.126.182 footstone/{PBE}BX6qwkwV8yF-dBwoM4K7P4qK4ege4mhz id=1 group=1",
    "d5k.co d5k:{PBE}0nZXJnR3ZeL3z3GYQbQwV6BtPkd0GbEl id=2 group=2",
]

# exec mode(0: cmd by cmd, 1 host by host)
execMode = 0
cmdTimeout = "30s"
# 全部命令都默认成远程执行，相当于自动添加了%host标识。
globalRemote = true

cmds = [
    "%local basename $PWD => @App",
    "%local make targz",
    "rm -fr bingoohuang/@App*",
    "%ul ../@App.tar.gz bingoohuang/",
    "cd bingoohuang && tar zxf @App.tar.gz && cd @App",
    "%host-1 go16 install -ldflags=\"-s -w\" ./...",
    "%host-2 export GOPROXY=https://goproxy.cn; go install -ldflags=\"-s -w\" ./...",
    "which @App => @Which",
    "upx --best --lzma  @Which",
    "ls -lh @Which",
    "@App -v",
    "%local rm -fr ~/Documents/@App",
    "%dl @Which ~/Documents",
    "%local ls -lh ~/Documents/@App",
]
