// +build !skippackr
// Code generated by github.com/gobuffalo/packr/v2. DO NOT EDIT.

// You can use the "packr2 clean" command to clean up this,
// and any other packr generated files.
package packrd

import (
	"github.com/gobuffalo/packr/v2"
	"github.com/gobuffalo/packr/v2/file/resolver"
)

var _ = func() error {
	const gk = "06108276ab7d899ea2485b8934f35cbd"
	g := packr.New(gk, "")
	hgr, err := resolver.NewHexGzip(map[string]string{
		"b006304051f3c876fd6daaa6e0931228": "1f8b08000000000000ffcc94cf8e9b3010c6ef3cc5dc9295d843afae7c20c9a4b5eac0d6987673426ced6a2d118882db55debe8204b0ebedb687fee384c6f6ccf71b8fbfdb5b68aa8326b03ee9ca6a593dd43a5a0b4c24824c561c816d21cd24e03dcb650e8fd61e6bf35597ba51c7d634365a46000046c1f4b154e21b147027d82e117b78877b480a99b1742d7087a98c87236386fe5fe2bd1ccaa405e750a4ec7d81975d076d1f5bd541b0ebba6c0ebab4e7a3be2e5fa29f4dad7b2cf0a20fad3a8f1ae7e8a701bcb4e6a09f2bf0e5a85e5a56bad656abb2b2a3bc82f3e8e675144d9de5556759d3e99315ed13db4439725c4ba8abce96668897a7f6c9a8a5776a6b1a85638faf478c8aa7aec56367e2b907f1041e0fb0b10b17bb28b1233cda8a6cf7ccc57e7c8b02fb8ba5b020af16df8b5b9dff0779d3108522b9e9ec28b1fb971a9d19a1b058407b72432cbfcc4c26362860b507a35c8a44cd63c0d21c85ecdf5716165bfe7eac9be843c20bcc6149e6e464ca4e9cf464ce4f2e0588578178258853e307b06cf313dc3f73930e725fe02f7117c3a6e99e8bbb4defbfe13ce5283ddba48ec0c02de92c39b04aea420496491dacc039e91534304feaa307ee49fd6604f649ddf6b8ee43fc17b11936fd5ab3bca7f752fa6f010000ffff5623b9f808070000",
	})
	if err != nil {
		panic(err)
	}
	g.DefaultResolver = hgr

	func() {
		b := packr.New("myBox", "assets")
		b.SetResolver("httplive.sql", packr.Pointer{ForwardBox: gk, ForwardPath: "b006304051f3c876fd6daaa6e0931228"})
	}()
	return nil
}()
