// +build !skippackr
// Code generated by github.com/gobuffalo/packr/v2. DO NOT EDIT.

// You can use the "packr2 clean" command to clean up this,
// and any other packr generated files.
package packrd

import (
	"github.com/gobuffalo/packr/v2"
	"github.com/gobuffalo/packr/v2/file/resolver"
)

var _ = func() error {
	const gk = "06108276ab7d899ea2485b8934f35cbd"
	g := packr.New(gk, "")
	hgr, err := resolver.NewHexGzip(map[string]string{
		"b006304051f3c876fd6daaa6e0931228": "1f8b08000000000000ffd495cd6edb3a1085f77a8ad9d90192c5ddf2820bd91eb7446529a5a8365e094ac9220464c9b0d8067efb427f1459a669372d10afac437286dff1e8f8ee0e9aeaa4086c2faa324a548fb58ab61c638120e24d82c0f6906602f081e522872763ceb5feae4ad5c873ab1b13ad2300002dc17e582af01d72b8e7ec10f3237cc023c485c858bae578c054dc0e47e60afd77810f62689316490245ca3e1638ee3a29f3d4ca0e825dd3b23ea9d25ccf6a5a1ed5afba563d1678ea632baff31d17f5cb005e1a7d522f35f87696af2d4b552ba3645999f97a45924437ff47917536a93ac39a4e5d0c6f9fd92eca31c1ad80baea4ca907bdbcb4cf5aaebd537bdd489c3d9e8e68393675ccb3c2e4d3f23c1b6395d9142bf47ed807c706ab39ec565b80a33dcf0e2f0cc4e7f7c8b11f080a2bf2dfea67a8cdf52d63d9a10de112dd9919ad7b8b6cce2c5358adfae3edc555593e8e77c677c86173042d5d0362b94c2c4b73e4a28f822cecb7b656580f1cf8857ac4f5383d40e76e37d1a73829308735598a135b9d38e5c9529f8c0d88d781782d88d3e317b06cf71b5c2d6fe1af22f70dfe1177316cb2bf7371bfebff2ac291ca5178094f9d0b06c14e972b07a94e5d8820dda98315843c9d40839ca73e7a10f4d43723487aeadae3061ef1df88ddb0e9cfccf2debed7caff080000ffff9adf7f71b3070000",
	})
	if err != nil {
		panic(err)
	}
	g.DefaultResolver = hgr

	func() {
		b := packr.New("myBox", "assets")
		b.SetResolver("httplive.sql", packr.Pointer{ForwardBox: gk, ForwardPath: "b006304051f3c876fd6daaa6e0931228"})
	}()
	return nil
}()
